import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final prefs = await SharedPreferences.getInstance();
  runApp(YeHidnistApp(prefs: prefs));
}

class AppState extends ChangeNotifier {
  AppState(this.prefs) {
    dark = prefs.getBool('dark') ?? false;
    name = prefs.getString('name') ?? 'Олексій Коваль';
    role = prefs.getString('role') ?? 'Учень';
    school = prefs.getString('school') ?? 'Ліцей №1';
    logged = prefs.getBool('logged') ?? false;
    messages = List<String>.from(prefs.getStringList('messages') ?? const []);
  }
  final SharedPreferences prefs;
  bool dark = false, logged = false;
  String name = '', role = '', school = '';
  List<String> messages = [];
  void setDark(bool v) { dark = v; prefs.setBool('dark', v); notifyListeners(); }
  void login(String n, String r, String s) { name=n; role=r; school=s; logged=true; prefs..setString('name',n)..setString('role',r)..setString('school',s)..setBool('logged',true); notifyListeners(); }
  void logout() { logged=false; prefs.setBool('logged',false); notifyListeners(); }
  void addMessage(String text) { messages=[...messages,text]; prefs.setStringList('messages', messages); notifyListeners(); }
}

class YeHidnistApp extends StatelessWidget {
  const YeHidnistApp({super.key, required this.prefs});
  final SharedPreferences prefs;
  @override Widget build(BuildContext context) => Root(prefs:prefs);
}

class Root extends StatefulWidget { const Root({super.key, required this.prefs}); final SharedPreferences prefs; @override State<Root> createState()=>_RootState(); }
class _RootState extends State<Root> {
  late final AppState state;
  @override void initState(){super.initState(); state=AppState(widget.prefs); state.addListener(_changed);}
  void _changed()=>setState((){});
  @override void dispose(){state.removeListener(_changed);state.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>MaterialApp(
    debugShowCheckedModeBanner:false, title:'Є-Гідність', themeMode:state.dark?ThemeMode.dark:ThemeMode.light,
    theme:buildTheme(false), darkTheme:buildTheme(true), home: state.logged ? Shell(state:state) : Access(state:state));
}

ThemeData buildTheme(bool dark){
  final seed=const Color(0xFF1769D2); final cs=ColorScheme.fromSeed(seedColor:seed,brightness:dark?Brightness.dark:Brightness.light);
  return ThemeData(useMaterial3:true,colorScheme:cs,brightness:dark?Brightness.dark:Brightness.light,scaffoldBackgroundColor:dark?const Color(0xFF08111D):const Color(0xFFF4F7FB),fontFamily:'sans',
    appBarTheme:const AppBarTheme(centerTitle:false,elevation:0), cardTheme:CardThemeData(elevation:0,margin:EdgeInsets.zero,shape:RoundedRectangleBorder(borderRadius:BorderRadius.all(Radius.circular(20)))),
    inputDecorationTheme:InputDecorationTheme(filled:true,fillColor:dark?const Color(0xFF101D2C):Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.all(Radius.circular(16)),borderSide:BorderSide.none),contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:15)),
  );
}

class Access extends StatelessWidget { const Access({super.key,required this.state}); final AppState state;
 @override Widget build(BuildContext c)=>Scaffold(body:DecoratedBox(decoration:BoxDecoration(gradient:LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[Theme.of(c).colorScheme.primary.withOpacity(.18),Theme.of(c).scaffoldBackgroundColor,Theme.of(c).colorScheme.primary.withOpacity(.06)])),child:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:620),child:Column(children:[
  const Brand(),SizedBox(height:28),Text('Цифровий простір твоєї школи',style:Theme.of(c).textTheme.displaySmall?.copyWith(fontWeight:FontWeight.w900),textAlign:TextAlign.center),const SizedBox(height:12),Text('Чати, класи, новини, цифровий ID та адміністративні інструменти — в одному місці.',textAlign:TextAlign.center,style:Theme.of(c).textTheme.titleMedium),const SizedBox(height:28),
  Row(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Expanded(child:ActionCard(icon:Icons.verified_user_rounded,title:'Підтвердити через Дію',text:'Демонстраційний захищений сценарій',onTap:()=>showDialog(context:c,builder:(_)=>LoginDialog(state:state)))),const SizedBox(width:14),Expanded(child:ActionCard(icon:Icons.qr_code_2_rounded,title:'Шкільний QR',text:'Швидке підключення до середовища',onTap:()=>showDialog(context:c,builder:(_)=>LoginDialog(state:state))))]),const SizedBox(height:18),
  Row(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.lock_outline,size:16,color:Theme.of(c).colorScheme.onSurfaceVariant),const SizedBox(width:6),Text('Локальний демонстраційний режим',style:Theme.of(c).textTheme.bodySmall)])
 ])))))); }
}
class LoginDialog extends StatefulWidget { const LoginDialog({super.key,required this.state}); final AppState state; @override State<LoginDialog> createState()=>_LoginDialogState(); }
class _LoginDialogState extends State<LoginDialog>{final n=TextEditingController(text:'Олексій Коваль');String r='Учень';String s='Ліцей №1';@override Widget build(BuildContext c)=>AlertDialog(title:const Text('Підтвердження особи'),content:SizedBox(width:430,child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Ім’я')),const SizedBox(height:10),DropdownButtonFormField<String>(initialValue:s,items:['Ліцей №1','Гімназія №2','Школа №3'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>s=v!),decoration:const InputDecoration(labelText:'Заклад')),const SizedBox(height:10),Wrap(spacing:7,children:['Учень','Вчитель','Батьки','Адміністратор'].map((x)=>ChoiceChip(label:Text(x),selected:r==x,onSelected:(_)=>setState(()=>r=x))).toList()),const SizedBox(height:10),const Row(children:[Icon(Icons.verified,color:Colors.green),SizedBox(width:8),Text('Особу підтверджено')])])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Скасувати')),FilledButton(onPressed:(){widget.state.login(n.text.trim().isEmpty?'Олексій Коваль':n.text,r,s);Navigator.pop(c);},child:const Text('Увійти'))]);}

class Shell extends StatefulWidget { const Shell({super.key,required this.state}); final AppState state; @override State<Shell> createState()=>_ShellState(); }
class _ShellState extends State<Shell>{int index=0;final pages=const [ChatsPage(),CommunitiesPage(),NewsPage(),ProfilePage()];@override Widget build(BuildContext c){final wide=MediaQuery.sizeOf(c).width>=900;return Scaffold(body:Row(children:[if(wide)SideBar(index:index,onTap:(i)=>setState(()=>index=i),state:widget.state),Expanded(child:IndexedStack(index:index,children:pages))]),bottomNavigationBar:wide?null:NavBar(index:index,onTap:(i)=>setState(()=>index=i),admin:widget.state.role=='Адміністратор'));}}

class SideBar extends StatelessWidget{const SideBar({super.key,required this.index,required this.onTap,required this.state});final int index;final ValueChanged<int> onTap;final AppState state;@override Widget build(BuildContext c)=>Container(width:250,padding:const EdgeInsets.fromLTRB(18,28,18,18),decoration:BoxDecoration(color:Theme.of(c).colorScheme.surface,border:Border(right:BorderSide(color:Theme.of(c).dividerColor))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Brand(compact:true),const SizedBox(height:30),for(final e in [(Icons.chat_bubble_outline,'Чати'),(Icons.groups_outlined,'Спільноти'),(Icons.newspaper_outlined,'Новини'),(Icons.person_outline,'Профіль')])SideItem(icon:e.$1,text:e.$2,selected:index==['Чати','Спільноти','Новини','Профіль'].indexOf(e.$2),onTap:()=>onTap(['Чати','Спільноти','Новини','Профіль'].indexOf(e.$2))),const Spacer(),ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(state.name,maxLines:1,overflow:TextOverflow.ellipsis),subtitle:Text(state.role)),if(state.role=='Адміністратор')ListTile(leading:const Icon(Icons.admin_panel_settings_outlined),title:const Text('Адмін-панель'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>AdminPage(state:state)))),ListTile(leading:const Icon(Icons.logout),title:const Text('Вийти'),onTap:state.logout)]);}
class SideItem extends StatelessWidget{const SideItem({super.key,required this.icon,required this.text,required this.selected,required this.onTap});final IconData icon;final String text;final bool selected;final VoidCallback onTap;@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(bottom:6),child: ListTile(leading:Icon(icon),title:Text(text,style:const TextStyle(fontWeight:FontWeight.w600)),selected:selected,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(14)),onTap:onTap));}

class NavBar extends StatelessWidget{const NavBar({super.key,required this.index,required this.onTap,required this.admin});final int index;final ValueChanged<int> onTap;final bool admin;@override Widget build(BuildContext c)=>NavigationBar(selectedIndex:index,onDestinationSelected:onTap,destinations:const [NavigationDestination(icon:Icon(Icons.chat_bubble_outline),selectedIcon:Icon(Icons.chat_bubble),label:'Чати'),NavigationDestination(icon:Icon(Icons.groups_outlined),selectedIcon:Icon(Icons.groups),label:'Спільноти'),NavigationDestination(icon:Icon(Icons.newspaper_outlined),selectedIcon:Icon(Icons.newspaper),label:'Новини'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Профіль')]);}

class ChatsPage extends StatefulWidget{const ChatsPage({super.key});@override State<ChatsPage>createState()=>_ChatsPageState();}
class _ChatsPageState extends State<ChatsPage>{String q='';final names=['8-Б • Клас','Учительська','Батьки 8-Б','Математика','Шкільні новини','Дирекція','Шаховий клуб','9-А • Клас','Історія','Медіацентр','Паралель 8-х','Адміністрація'];@override Widget build(BuildContext c){final list=names.where((x)=>x.toLowerCase().contains(q.toLowerCase())).toList();return PageFrame(title:'Чати',subtitle:'Спілкування школи',actions:[IconButton(onPressed:()=>showSearch(context:context,delegate:ChatSearch(names)),icon:const Icon(Icons.search)),IconButton(onPressed:()=>showDialog(context:context,builder:(_)=>const NewChatDialog()),icon:const Icon(Icons.add_comment_outlined))],child:ListView.separated(padding:const EdgeInsets.fromLTRB(20,0,20,30),itemCount:list.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(c,i)=>ChatTile(name:list[i],unread:i%4==0,onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ChatPage(name:list[i])))));}}
class ChatSearch extends SearchDelegate<String>{ChatSearch(this.names);final List<String>names;@override List<Widget>?buildActions(BuildContext c)=>[IconButton(onPressed:()=>query='',icon:const Icon(Icons.clear))];@override Widget?buildLeading(BuildContext c)=>BackButton(onPressed:()=>close(c,''));@override Widget buildResults(BuildContext c)=>ListView(children:names.where((x)=>x.toLowerCase().contains(query.toLowerCase())).map((x)=>ListTile(title:Text(x),onTap:()=>close(c,x))).toList());@override Widget buildSuggestions(BuildContext c)=>buildResults(c);}
class NewChatDialog extends StatelessWidget{const NewChatDialog({super.key});@override Widget build(BuildContext c)=>AlertDialog(title:const Text('Новий чат'),content:const Text('У демо можна відкрити готові шкільні чати. Підключення реального бекенду додається окремо.'),actions:[FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Готово'))]);}
class ChatTile extends StatelessWidget{const ChatTile({super.key,required this.name,required this.unread,required this.onTap});final String name;final bool unread;final VoidCallback onTap;@override Widget build(BuildContext c)=>Card(child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:14,vertical:8),leading:CircleAvatar(radius:25,child:Text(name.substring(0,1))),title:Text(name,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:const Text('Останнє повідомлення • сьогодні'),trailing:unread?Badge(label:const Text('2')):const Icon(Icons.chevron_right),onTap:onTap));}

class ChatPage extends StatefulWidget{const ChatPage({super.key,required this.name});final String name;@override State<ChatPage>createState()=>_ChatPageState();}
class _ChatPageState extends State<ChatPage>{final ctrl=TextEditingController();final msgs=['Привіт!','Нагадую про подію завтра.','Все готово 👍','Дякую!','До зустрічі.'];@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Row(children:[CircleAvatar(child:Text(widget.name.substring(0,1))),const SizedBox(width:10),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(widget.name,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w700)),const Text('12 учасників',style:TextStyle(fontSize:11))])]),actions:[IconButton(onPressed:(){},icon:const Icon(Icons.more_vert))]),body:Column(children:[Expanded(child:ListView.builder(reverse:true,padding:const EdgeInsets.all(16),itemCount:msgs.length,itemBuilder:(c,i)=>Align(alignment:i.isEven?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.symmetric(horizontal:14,vertical:10),constraints:const BoxConstraints(maxWidth:330),decoration:BoxDecoration(color:i.isEven?Theme.of(c).colorScheme.primary:Theme.of(c).colorScheme.surface,borderRadius:BorderRadius.circular(18),border:i.isEven?null:Border.all(color:Theme.of(c).dividerColor)),child:Text(msgs[msgs.length-1-i]))))),SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(12,5,12,12),child:Row(children:[Expanded(child:TextField(controller:ctrl,minLines:1,maxLines:4,decoration:const InputDecoration(hintText:'Написати повідомлення',prefixIcon:Icon(Icons.add)))),const SizedBox(width:8),IconButton.filled(onPressed:(){if(ctrl.text.trim().isNotEmpty){setState((){msgs.add(ctrl.text.trim());ctrl.clear();});}},icon:const Icon(Icons.send))])))]);}

class CommunitiesPage extends StatelessWidget{const CommunitiesPage({super.key});final data=const [('Робототехніка',48,Icons.smart_toy),('Шаховий клуб',24,Icons.extension),('Медіацентр',31,Icons.movie),('Волонтерський центр',62,Icons.volunteer_activism),('Спорт',75,Icons.sports_soccer),('Учнівське самоврядування',19,Icons.how_to_vote)];@override Widget build(BuildContext c)=>PageFrame(title:'Спільноти',subtitle:'Клуби, гуртки та шкільні групи',actions:[IconButton(onPressed:(){},icon:const Icon(Icons.search))],child:GridView.builder(padding:const EdgeInsets.fromLTRB(20,0,20,30),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:MediaQuery.sizeOf(c).width>800?3:MediaQuery.sizeOf(c).width>520?2:1,mainAxisExtent:170,crossAxisSpacing:12,mainAxisSpacing:12),itemCount:data.length,itemBuilder:(c,i){final d=data[i];return Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[CircleAvatar(child:Icon(d.$3)),const Spacer(),Text(d.$1,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800)),const SizedBox(height:5),Text('${d.$2} учасників • Активна',style:Theme.of(c).textTheme.bodySmall)])));}));}

class NewsPage extends StatelessWidget{const NewsPage({super.key});final titles=const ['Олімпіада з математики','День школи','Новий гурток робототехніки','Тиждень безпеки','Спортивні змагання','Відкриття медіацентру'];@override Widget build(BuildContext c)=>PageFrame(title:'Новини',subtitle:'Важливі події школи',actions:[IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none))],child:ListView.separated(padding:const EdgeInsets.fromLTRB(20,0,20,30),itemCount:titles.length,separatorBuilder:(_,__)=>const SizedBox(height:12),itemBuilder:(c,i)=>Card(child:InkWell(borderRadius:BorderRadius.circular(20),onTap:()=>showModalBottomSheet(context:c,showDragHandle:true,builder:(_)=>Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(titles[i],style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:10),const Text('Подія школи з детальною інформацією, датою, організаторами та важливими нагадуваннями.'),const SizedBox(height:20),FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Закрити'))])),child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[Container(width:72,height:72,decoration:BoxDecoration(color:Theme.of(c).colorScheme.primaryContainer,borderRadius:BorderRadius.circular(16)),child:Icon([Icons.calculate,Icons.celebration,Icons.smart_toy,Icons.security,Icons.sports,Icons.perm_media][i],size:32)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(titles[i],style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800)),const SizedBox(height:6),Text('${i+1} день тому • Є-Гідність',style:Theme.of(c).textTheme.bodySmall)])),const Icon(Icons.chevron_right)]))));}

class ProfilePage extends StatelessWidget{const ProfilePage({super.key});@override Widget build(BuildContext c){final root=c.findAncestorStateOfType<_ShellState>()!;final s=root.widget.state;return PageFrame(title:'Профіль',subtitle:'Ваш цифровий простір',actions:[IconButton(onPressed:()=>s.setDark(!s.dark),icon:Icon(s.dark?Icons.light_mode:Icons.dark_mode)),IconButton(onPressed:()=>showModalBottomSheet(context:c,showDragHandle:true,builder:(_)=>const SettingsSheet()),icon:const Icon(Icons.settings_outlined))],child:ListView(padding:const EdgeInsets.fromLTRB(20,0,20,30),children:[Card(child:Padding(padding:const EdgeInsets.all(20),child:Row(children:[const CircleAvatar(radius:36,child:Icon(Icons.person,size:36)),const SizedBox(width:15),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(s.name,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),Text('${s.role} • ${s.school}'),const SizedBox(height:8),const Chip(avatar:Icon(Icons.verified,size:16,color:Colors.green),label:Text('Підтверджено'))]))])),const SizedBox(height:14),DigitalId(name:s.name,role:s.role,school:s.school),const SizedBox(height:14),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,mainAxisSpacing:10,crossAxisSpacing:10,childAspectRatio:2.2,children:[ProfileAction(icon:Icons.qr_code_2,title:'Мій QR',onTap:()=>showDialog(context:c,builder:(_)=>const QrDialog())),ProfileAction(icon:Icons.qr_code_scanner,title:'Сканувати',onTap:()=>showDialog(context:c,builder:(_)=>const ScanDialog())),ProfileAction(icon:Icons.security,title:'Безпека',onTap:()=>showDialog(context:c,builder:(_)=>const SecurityDialog())),ProfileAction(icon:Icons.badge_outlined,title:'Мої дані',onTap:()=>showDialog(context:c,builder:(_)=>const DataDialog()))]),const SizedBox(height:14),Card(child:Column(children:[ListTile(leading:const Icon(Icons.school_outlined),title:const Text('Мій клас'),subtitle:const Text('8-Б • 24 учні'),trailing:const Icon(Icons.chevron_right)),const Divider(height:1),ListTile(leading:const Icon(Icons.calendar_month_outlined),title:const Text('Розклад'),subtitle:const Text('6 уроків сьогодні'),trailing:const Icon(Icons.chevron_right))])),const SizedBox(height:10),OutlinedButton.icon(onPressed:s.logout,icon:const Icon(Icons.logout),label:const Text('Вийти з акаунта'))]));}}

class DigitalId extends StatelessWidget{const DigitalId({super.key,required this.name,required this.role,required this.school});final String name,role,school;@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:LinearGradient(colors:[Theme.of(c).colorScheme.primary,Theme.of(c).colorScheme.primary.withOpacity(.72)]),borderRadius:BorderRadius.circular(24)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('Є-ГІДНІСТЬ ID',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,letterSpacing:1.2)),Icon(Icons.verified,color:Colors.white.withOpacity(.9))]),const SizedBox(height:22),Row(children:[const CircleAvatar(radius:30,child:Icon(Icons.person)),const SizedBox(width:14),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name,style:const TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w900)),Text(role,style:const TextStyle(color:Colors.white70)),Text(school,style:const TextStyle(color:Colors.white70))])]),const SizedBox(height:18),const Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('СТАТУС  •  ПІДТВЕРДЖЕНО',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800,fontSize:11)),Text('ID: 8B-0428',style:TextStyle(color:Colors.white70,fontSize:11))])]);}
class ProfileAction extends StatelessWidget{const ProfileAction({super.key,required this.icon,required this.title,required this.onTap});final IconData icon;final String title;final VoidCallback onTap;@override Widget build(BuildContext c)=>Card(child:InkWell(borderRadius:BorderRadius.circular(20),onTap:onTap,child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,color:Theme.of(c).colorScheme.primary),const SizedBox(width:8),Text(title,style:const TextStyle(fontWeight:FontWeight.w700))])));}
class SettingsSheet extends StatelessWidget{const SettingsSheet({super.key});@override Widget build(BuildContext c)=>const SafeArea(child:Padding(padding:EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Налаштування',style:TextStyle(fontSize:22,fontWeight:FontWeight.w800)),SizedBox(height:15),ListTile(leading:Icon(Icons.notifications_outlined),title:Text('Сповіщення'),subtitle:Text('Усі важливі події')),ListTile(leading:Icon(Icons.language),title:Text('Мова'),subtitle:Text('Українська')),ListTile(leading:Icon(Icons.palette_outlined),title:Text('Оформлення'),subtitle:Text('Світле або темне'))]));}
class SecurityDialog extends StatelessWidget{const SecurityDialog({super.key});@override Widget build(BuildContext c)=>const AlertDialog(title:Text('Безпека'),content:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(leading:Icon(Icons.verified_user,color:Colors.green),title:Text('Дія підтверджена'),subtitle:Text('Сесія активна')),ListTile(leading:Icon(Icons.devices),title:Text('Пристрій'),subtitle:Text('Поточний Android-пристрій')),ListTile(leading:Icon(Icons.history),title:Text('Журнал входів'),subtitle:Text('3 локальні події'))]));}
class DataDialog extends StatelessWidget{const DataDialog({super.key});@override Widget build(BuildContext c)=>const AlertDialog(title:Text('Мої дані'),content:Text('Ім’я, роль, заклад та клас зберігаються локально в демонстраційному режимі. Реальні персональні дані не підключені.'));}

class QrDialog extends StatefulWidget{const QrDialog({super.key});@override State<QrDialog>createState()=>_QrState();}class _QrState extends State<QrDialog>{late Timer timer;int seconds=300;@override void initState(){super.initState();timer=Timer.periodic(const Duration(seconds:1),(_){if(mounted)setState(()=>seconds=max(0,seconds-1));});}@override void dispose(){timer.cancel();super.dispose();}@override Widget build(BuildContext c)=>AlertDialog(title:const Text('Мій QR-код'),content:Column(mainAxisSize:MainAxisSize.min,children:[const QrVisual(),const SizedBox(height:12),Text('Дійсний ще ${seconds~/60}:${(seconds%60).toString().padLeft(2,'0')}'),const SizedBox(height:8),const Text('Покажіть код педагогові для демонстраційного підключення.',textAlign:TextAlign.center,style:TextStyle(fontSize:12))]));}
class ScanDialog extends StatefulWidget{const ScanDialog({super.key});@override State<ScanDialog>createState()=>_ScanDialogState();}class _ScanDialogState extends State<ScanDialog>{int step=0;@override Widget build(BuildContext c)=>AlertDialog(title:const Text('Сканування QR'),content:Column(mainAxisSize:MainAxisSize.min,children:[Container(width:230,height:230,decoration:BoxDecoration(border:Border.all(color:Theme.of(c).colorScheme.primary,width:3),borderRadius:BorderRadius.circular(24)),child:Icon(step==0?Icons.qr_code_scanner:Icons.check_circle,size:80,color:Theme.of(c).colorScheme.primary)),const SizedBox(height:15),Text(step==0?'Наведіть камеру на QR-код':'Знайдено: Дмитро • 8-Б'),const SizedBox(height:14),FilledButton(onPressed:()=>setState(()=>step=1-step),child:Text(step==0?'Імітувати сканування':'Готово'))]));}
class QrVisual extends StatelessWidget{const QrVisual({super.key});@override Widget build(BuildContext c)=>Container(width:230,height:230,padding:14,color:Colors.white,child:CustomPaint(painter:QrPainter()));}class QrPainter extends CustomPainter{@override void paint(Canvas canvas,Size size){final p=Paint()..color=Colors.black;final r=Random(42);final n=25;final cell=size.width/n;for(int y=0;y<n;y++){for(int x=0;x<n;x++){if(r.nextDouble()>.53)canvas.drawRect(Rect.fromLTWH(x*cell,y*cell,cell-.5,cell-.5),p);}}for(final o in [Offset(1,1),Offset(n-8,1),Offset(1,n-8)]){canvas.drawRect(Rect.fromLTWH(o.dx*cell,o.dy*cell,7*cell,7*cell),p..color=Colors.black);canvas.drawRect(Rect.fromLTWH((o.dx+1)*cell,(o.dy+1)*cell,5*cell,5*cell),p..color=Colors.white);canvas.drawRect(Rect.fromLTWH((o.dx+2)*cell,(o.dy+2)*cell,3*cell,3*cell),p..color=Colors.black);}}@override bool shouldRepaint(covariant CustomPainter oldDelegate)=>false;}

class AdminPage extends StatefulWidget{const AdminPage({super.key,required this.state});final AppState state;@override State<AdminPage>createState()=>_AdminPageState();}
class _AdminPageState extends State<AdminPage>{int tab=0;final tabs=['Огляд','Користувачі','Класи','Новини','Модерація','Скарги','Журнал'];@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Адмін-панель'),actions:[IconButton(onPressed:()=>widget.state.setDark(!widget.state.dark),icon:Icon(widget.state.dark?Icons.light_mode:Icons.dark_mode))]),body:Column(children:[SingleChildScrollView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.all(12),child:Row(children:List.generate(tabs.length,(i)=>Padding(padding:const EdgeInsets.only(right:7),child:ChoiceChip(label:Text(tabs[i]),selected:tab==i,onSelected:(_)=>setState(()=>tab=i)))))),Expanded(child:tab==0?_AdminOverview():ListView.builder(padding:const EdgeInsets.all(16),itemCount:tab==1?18:tab==2?7:tab==3?6:tab==4?8:tab==5?6:25,itemBuilder:(c,i)=>Card(child:ListTile(leading:CircleAvatar(child:Text('${i+1}')),title:Text('${tabs[tab]} • запис №${i+1}'),subtitle:const Text('Демонстраційний запис • локальне збереження'),trailing:const Icon(Icons.chevron_right)))))]));}}
class _AdminOverview extends StatelessWidget{@override Widget build(BuildContext c){final data=[('Користувачі','1 248',Icons.people),('Класи','42',Icons.class_),('Чати','86',Icons.chat),('Повідомлення','12 490',Icons.forum),('Новини','126',Icons.newspaper),('Скарги','8',Icons.report_problem)];return GridView.builder(padding:const EdgeInsets.all(16),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:MediaQuery.sizeOf(c).width>900?3:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.45),itemCount:data.length,itemBuilder:(c,i){final d=data[i];return Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(d.$3,color:Theme.of(c).colorScheme.primary,size:28),const Spacer(),Text(d.$2,style:const TextStyle(fontSize:27,fontWeight:FontWeight.w900)),Text(d.$1,style:Theme.of(c).textTheme.bodySmall)])));});}}

class PageFrame extends StatelessWidget{const PageFrame({super.key,required this.title,required this.subtitle,required this.child,this.actions=const []});final String title,subtitle;final Widget child;final List<Widget> actions;@override Widget build(BuildContext c)=>SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(20,18,12,14),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:Theme.of(c).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w900)),Text(subtitle,style:Theme.of(c).textTheme.bodyMedium?.copyWith(color:Theme.of(c).colorScheme.onSurfaceVariant))])),...actions])),Expanded(child:child)]));}
class Brand extends StatelessWidget{const Brand({super.key,this.compact=false});final bool compact;@override Widget build(BuildContext c)=>Row(mainAxisSize:MainAxisSize.min,children:[Container(width:compact?40:52,height:compact?40:52,decoration:BoxDecoration(color:Theme.of(c).colorScheme.primary,borderRadius:BorderRadius.circular(15),boxShadow:[BoxShadow(color:Theme.of(c).colorScheme.primary.withOpacity(.25),blurRadius:18)]),alignment:Alignment.center,child:Text('Є',style:TextStyle(color:Colors.white,fontSize:compact?21:28,fontWeight:FontWeight.w900)),),const SizedBox(width:10),Text('Є-Гідність',style:Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900))]);}
class ActionCard extends StatelessWidget{const ActionCard({super.key,required this.icon,required this.title,required this.text,required this.onTap});final IconData icon;final String title,text;final VoidCallback onTap;@override Widget build(BuildContext c)=>Card(child:InkWell(borderRadius:BorderRadius.circular(20),onTap:onTap,child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,size:34,color:Theme.of(c).colorScheme.primary),const Spacer(),Text(title,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w800)),const SizedBox(height:5),Text(text,style:Theme.of(c).textTheme.bodySmall)]))));}
